id: I6AC84865
legacy_id: P006686
ocr_import_info:
  bdrc_scan_id: W23370
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T04:21:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:01:50.148869+00:00'
last_modified: 2022-09-02 09:02:03.317948
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23370
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23370
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫ་དཔལ་སྤྲུལ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོའི་གསུང་ཐོར་བུ།
  author: རྫ་དཔལ་སྤྲུལ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6043244773057272
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I1552:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1552
      total_pages: 610
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1552.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6043244773057272
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
